# =============================================================
# AirWatch - PERFIL: prod (Render + banco FIAP)
# =============================================================

# Banco FIAP (acessivel externamente)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@//oracle.fiap.com.br:1521/orcl}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:RM565760}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:150606}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.defer-datasource-initialization=true
spring.datasource.hikari.initialization-fail-timeout=-1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=3

# JWT
airwatch.jwt.secret=${AIRWATCH_JWT_SECRET:AirWatchSolsticioFIAP2026SecretKeyBase64EncodedMinimo256bits}
airwatch.jwt.expiration=${AIRWATCH_JWT_EXPIRATION:86400000}

# Porta dinamica (Render injeta PORT)
server.port=${PORT:8080}
